minimum_pre_commit_version: '3.1'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      # check for unresolved merge conflicts
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
      - id: golangci-lint
        # timeout is needed for CI
        args: [ -E, gosec, -E, goconst, -E, govet, --timeout, 300s ]
      - id: go-imports
        args: [ -local, github.com/rossf7/carbon-aware-karmada-operator ]
      - id: go-unit-tests
